tv_show_manager_episode:
    resource: "@TvShowManagerBundle/Controller/EpisodeController.php"
    type:     annotation

tv_show_manager_tv_show:
    resource: "@TvShowManagerBundle/Controller/TvShowController.php"
    type:     annotation

tv_show_manager:
    resource: "@TvShowManagerBundle/Resources/config/routing.yml"
    prefix:   /

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

